### ISSUE TITLE
Push access to the Docker hub adtd org

### ISSUE THREAD

**Issue by lingmann** [rgardler/AzureDevTestDeploy#16]
Could someone grant my Docker Hub user id (lingmann) push access to the [adtd org](https://hub.docker.com/u/adtd/)? I'm running through the ACS [automated deployment](https://github.com/rgardler/AzureDevTestDeploy/tree/master/demo/demo250_automated_deployment#details-1) demo script. Thanks!

**Comment by squillace** [comment]
@lingmann @rgardler will have to arrange this, but more generally, do you mean you can't submit a PR? What do you need "push" for? I don't care -- I'd love you to push all over, bucko -- but I'm curious what you're wanting to do... 

BTW: I demo'd this one in barcelona, and had to port the preparation scripts to mac/zsh, so if you want those.... I can pass them to you. I used tmuxinator with iterm2 and it works perfectly....

**Comment by rgardler** [comment]
@Lingmann - done
